name: Build and publish C++ with cl.exe

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

      # https://github.com/marketplace/actions/enable-developer-command-prompt
    - name: Set up C/C++ tooling
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create output folder
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run : mkdir bin

    - name: Build with cl.exe - release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        ./build.bat
        mv git-credential-keyed-helper.exe .\bin

    - name: Build with cl.exe - debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        ./build-debug.bat
        mv git-credential-keyed-helper.exe .\bin\git-credential-keyed-helper-debug.exe

      # https://github.com/marketplace/actions/create-release
    - name: Create release
      id: create-release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"
